apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: ruby-helloworld-sample
    name: ruby-sample-build
    template: application-template-stibuild
  name: ruby-sample-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: origin-ruby-sample:latest
  postCommit:
    args:
    - bundle
    - exec
    - rake
    - test
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/openshift/ruby-hello-world.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: EXAMPLE
        value: sample-app
      from:
        kind: ImageStreamTag
        name: ruby:latest
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      allowEnv: true
      secret: secret101
    type: Generic
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
status:
  lastVersion: 0
